### ISSUE TITLE
Rewrite application based off of new UI designs

### ISSUE THREAD

**Issue by DGKSK8LIFE** [radrob1/helium-place#12]
![image](https://user-images.githubusercontent.com/45473363/106537503-13959280-64c0-11eb-80c0-bd93f3f0dc50.png)

**Comment by radrob1** [comment]
i like these new designs - cleaner and more mobile friendly. I think it needs a sidebar menu for the map options so that the resolution hexes can be displayed + any other map configurations we come up with, but hidden out of view so it doesn't take up screen real estate. Feel free to move forward with this design.

**Comment by DGKSK8LIFE** [comment]
> i like these new designs - cleaner and more mobile friendly. I think it needs a sidebar menu for the map options so that the resolution hexes can be displayed + any other map configurations we come up with, but hidden out of view so it doesn't take up screen real estate. Feel free to move forward with this design.

Feel free to add any additional wireframes/prototypes in the figma for the functionality you want. Will see about programming the new UI soon

**Comment by radrob1** [comment]
Branch https://github.com/radrob1/helium-place/tree/refactor-issue-13

**Comment by radrob1** [comment]
merged in dev #23

**Comment by radrob1** [comment]
merged to main in #27
